version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL=postgres://postgres:1001@db:5432/bitcoin_history

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1001
      - POSTGRES_DB=bitcoin_history
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
